In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('./Datasets/titanic.csv')
dfdf

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [5]:
data = {'ID':[1,2,3,4,5],
        'Name':['Amit','Priya',np.nan,'Rahul',np.nan],
        'Marks':[80,np.nan,75,85,np.nan],
        'city':['Ahm','BVN',np.nan,'Surat','Rajkot']}
df = pd.DataFrame(data)
df

   ID   Name  Marks    city
0   1   Amit   80.0     Ahm
1   2  Priya    NaN     BVN
2   3    NaN   75.0     NaN
3   4  Rahul   85.0   Surat
4   5    NaN    NaN  Rajkot

In [7]:
df.isnull()

      ID   Name  Marks   city
0  False  False  False  False
1  False  False   True  False
2  False   True  False   True
3  False  False  False  False
4  False   True   True  False

In [9]:
df.isnull().sum()

ID       0
Name     2
Marks    2
city     1
dtype: int64